import {createSlice} from "@reduxjs/toolkit";

const AdminUpDelUser=createSlice({
    name:"AdminUpDelUser",
    initialState:{user:{}},
    reducers:{
        adminGetUserRequest(state,action){
            return{
                ...state,
                loading:true
            }
        },
        adminGetUserSuccess(state,action){
            return{
                ...state,
                loading:false,
                user:action.payload
            }
        },
        adminGetUserFail(state,action){
            return{
                ...state,
                loading:false,
                error:action.payload
            }
        },
        adminUpdateUserRequest(state,action){
            return{
                ...state,
                loading:true,
            }
        },
        adminUpdateUserSuccess(state,action){
            return{
                ...state,
                loading:false,
                isUpdated:action.payload.success,
                message:action.payload.message
            }
        },
        adminUpdateUserFail(state,action){
            return{
                ...state,
                loading:false,
                error:action.payload
            }
        },
        adminUpdateUserReset(state,action){
            return{
                ...state,
                isUpdated:false
            }
        },
        adminDelUserRequest(state,action){
            return{
                ...state,
                loading:true,
            }
        },
        adminDelUserSuccess(state,action){
            return{
                ...state,
                loading:false,
                isDeleted:action.payload.success,
                message:action.payload.message
            }
        },
        adminDelUserFail(state,action){
            return{
                ...state,
                loading:false,
                error:action.payload
            }
        },
        adminDelUserReset(state,action){
            return{
                ...state,
                isDeleted:false
            }
        },
        clearError(state,action){
            return {
                ...state,
                error:null
            }
        },
    }
})
export default AdminUpDelUser.reducer;
export const {adminGetUserRequest,adminGetUserSuccess,adminGetUserFail,adminUpdateUserRequest,adminUpdateUserSuccess,adminUpdateUserFail,adminUpdateUserReset,adminDelUserRequest,adminDelUserSuccess,adminDelUserFail,adminDelUserReset,clearError} = AdminUpDelUser.actions;